<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\Query\Query;
use Doctrine\ODM\MongoDB\UnitOfWork;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadataInfo;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class AppModelsManagerHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id']) || (! empty($this->class->fieldMappings['id']['nullable']) && array_key_exists('_id', $data))) {
            $value = $data['_id'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['id']['type'];
                $return = $value instanceof \MongoId ? (string) $value : $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['changes']) || (! empty($this->class->fieldMappings['changes']['nullable']) && array_key_exists('changes', $data))) {
            $value = $data['changes'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['changes']['type'];
                $return = (int) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['changes']->setValue($document, $return);
            $hydratedData['changes'] = $return;
        }

        /** @Field(type="collection") */
        if (isset($data['notes']) || (! empty($this->class->fieldMappings['notes']['nullable']) && array_key_exists('notes', $data))) {
            $value = $data['notes'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['notes']['type'];
                $return = $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['notes']->setValue($document, $return);
            $hydratedData['notes'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['name']) || (! empty($this->class->fieldMappings['name']['nullable']) && array_key_exists('name', $data))) {
            $value = $data['name'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['name']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['name']->setValue($document, $return);
            $hydratedData['name'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['salary']) || (! empty($this->class->fieldMappings['salary']['nullable']) && array_key_exists('salary', $data))) {
            $value = $data['salary'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['salary']['type'];
                $return = (int) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['salary']->setValue($document, $return);
            $hydratedData['salary'] = $return;
        }

        /** @Field(type="date") */
        if (isset($data['started'])) {
            $value = $data['started'];
            if ($value === null) { $return = null; } else { $return = \Doctrine\ODM\MongoDB\Types\DateType::getDateTime($value); }
            $this->class->reflFields['started']->setValue($document, clone $return);
            $hydratedData['started'] = $return;
        }

        /** @Field(type="date") */
        if (isset($data['left'])) {
            $value = $data['left'];
            if ($value === null) { $return = null; } else { $return = \Doctrine\ODM\MongoDB\Types\DateType::getDateTime($value); }
            $this->class->reflFields['left']->setValue($document, clone $return);
            $hydratedData['left'] = $return;
        }

        /** @EmbedOne */
        if (isset($data['address'])) {
            $embeddedDocument = $data['address'];
            $className = $this->unitOfWork->getClassNameForAssociation($this->class->fieldMappings['address'], $embeddedDocument);
            $embeddedMetadata = $this->dm->getClassMetadata($className);
            $return = $embeddedMetadata->newInstance();

            $this->unitOfWork->setParentAssociation($return, $this->class->fieldMappings['address'], $document, 'address');

            $embeddedData = $this->dm->getHydratorFactory()->hydrate($return, $embeddedDocument, $hints);
            $embeddedId = $embeddedMetadata->identifier && isset($embeddedData[$embeddedMetadata->identifier]) ? $embeddedData[$embeddedMetadata->identifier] : null;

            if (empty($hints[Query::HINT_READ_ONLY])) {
                $this->unitOfWork->registerManaged($return, $embeddedId, $embeddedData);
            }

            $this->class->reflFields['address']->setValue($document, $return);
            $hydratedData['address'] = $return;
        }

        /** @Many */
        $mongoData = isset($data['projects']) ? $data['projects'] : null;
        $return = $this->dm->getConfiguration()->getPersistentCollectionFactory()->create($this->dm, $this->class->fieldMappings['projects']);
        $return->setHints($hints);
        $return->setOwner($document, $this->class->fieldMappings['projects']);
        $return->setInitialized(false);
        if ($mongoData) {
            $return->setMongoData($mongoData);
        }
        $this->class->reflFields['projects']->setValue($document, $return);
        $hydratedData['projects'] = $return;
        return $hydratedData;
    }
}